# Generated by Django 2.0.7 on 2018-07-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consolelog_app', '0005_auto_20180719_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='bio',
        ),
    ]
