# Generated by Django 2.0.7 on 2018-07-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolelog_app', '0007_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
