# Generated by Django 2.0.7 on 2018-07-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolelog_app', '0009_auto_20180724_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timestamp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(default='./../static/src/components/Images/default-profile.jpg', upload_to='profile_image'),
        ),
    ]
