# Generated by Django 2.0.7 on 2018-07-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consolelog_app', '0010_auto_20180726_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='descripton',
        ),
    ]
