# Generated by Django 2.0.7 on 2018-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolelog_app', '0011_auto_20180730_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='descripton',
            field=models.CharField(default='', max_length=250),
        ),
    ]
