# Generated by Django 2.0.7 on 2018-07-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolelog_app', '0012_auto_20180731_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
