# Generated by Django 2.0.7 on 2018-07-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolelog_app', '0013_games_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descripton',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='./../static/src/components/Images/default-profile.jpg', upload_to='profile_image'),
        ),
    ]
