# Generated by Django 2.0.7 on 2018-07-31 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consolelog_app', '0014_auto_20180731_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='descripton',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='descripton',
            new_name='description',
        ),
    ]
