# Generated by Django 2.0.7 on 2018-07-31 21:53

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('consolelog_app', '0015_auto_20180731_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
