# Generated by Django 2.0.7 on 2018-07-31 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consolelog_app', '0017_auto_20180731_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='idgb_id',
            new_name='igdb_id',
        ),
    ]
