# Generated by Django 2.0.7 on 2018-07-31 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consolelog_app', '0019_auto_20180731_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platforms',
        ),
    ]
