# Generated by Django 2.0.7 on 2018-08-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consolelog_app', '0020_remove_game_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
